### ISSUE TITLE
读取配置文件失败

### ISSUE THREAD

**Issue by MingyangHuang** [kun775/douyinhelper#2]
**************************************************
               抖音下载小助手
     作者: HuangSK  Date: 2021-01-21 13:14
**************************************************
读取配置文件失败，请确保配置正确，按任意键继续

按要求把配置文件里的链接改了 其他都没有动，请问是什么情况

**Comment by MingyangHuang** [comment]
然后没有介绍里面说的exe file

**Comment by kun775** [comment]
配置文件要用SublimeText或NotePad++编辑，exe文件在Release处下载
